# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Abstraction.blog
description: > # this means to ignore newlines until "baseurl:"
  Valar Codilis. All men must code.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://abstraction.blog" # the base hostname & protocol for your site, e.g. http://example.com
author: Rohit Hegde
github_username:  rohithegde

#https://www.webpagefx.com/tools/emoji-cheat-sheet/
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  smart_quotes:   lsquo,rsquo,ldquo,rdquo

theme: jekyll-theme-cayman
# cayman, primer, architect
plugins:
  - jekyll-feed
  - jekyll-archives
  - jemoji
  
google_analytics: UA-60000051-1

#tag_page_layout: tag_page
tag_page_dir: '/archives/tags/'
#tag_feed_layout: tag_feed
#tag_feed_dir: tag
#tag_permalink_style: pretty

jekyll-archives:
  enabled:
    - year
    - month
    - day
    - tags
  layouts:
    year: archive_year
    month: archive_month
    day: archive_day
    tag: archive_tag
  permalinks:
    year: '/archives/time/:year/'
    month: '/archives/time/:year/:month/'
    day: '/archives/time/:year/:month/:day/'
    tag: '/archives/tags/:name/'

# The release of Jekyll Now that you're using
version: v3.5.2

permalink: /:year/:month/:day/:title

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
